### ISSUE TITLE
pyATS IOSXE Error on Step36: Store Data - parsed_show_issue_state

### ISSUE THREAD

**Issue by msiegy** [automateyournetwork/magic_carpet#114]
**Describe the bug**
When running the IOS-XE pyats Job:  pyats run job IOS_XE_magic_carpet_job.py --testbed-file testbed/testbed_c9300.yaml the scripts starts to collect data but crashes on Step36, with the following error:

![image](https://user-images.githubusercontent.com/13123548/117713271-71aed180-b1a3-11eb-9dda-e9a264b2e49b.png)

**To Reproduce**
run pyats job against c9300, c9500, or iosv devices. All produce the same error.

**Expected behavior**
Collect and store output in cave of wonders

**Desktop (please complete the following information):**
 - OS: Centos 8

**Additional context**
I've tried different platforms as well as modifying the platform value in the testbed.

**Comment by msiegy** [comment]
Hi - Slightly different problem now.
![image](https://user-images.githubusercontent.com/13123548/117812901-62299a00-b230-11eb-998e-8e88421e8643.png)
![image](https://user-images.githubusercontent.com/13123548/117812980-81c0c280-b230-11eb-9740-2bc9f7ada606.png)

**Comment by automateyournetwork** [comment]
can you try it now? I have added another platform handler

**Comment by automateyournetwork** [comment]
Well we are at least past ISSU! 

do you have VRFs on the device? 

I see the problem hang tight I will try to patch this right now for you

**Comment by automateyournetwork** [comment]
ok I've added a test (if self.parsed_show_ip_route_vrf) let me know
