### ISSUE TITLE
Problem getting netjsongraph to work

### ISSUE THREAD

**Issue by NetworkingB2A** [automateyournetwork/magic_carpet#90]
It appears that the files for the netjsongraph app to run is looking for files in the root directory.

When I run the local http server i can have the webpage come up, I navagate to the file i am trying to open.
When i open the mind map html document, the webpage loads and works great.
When i try to load the netgraph html document, the screen is just blank.

here is my error i receive on the server when i open the page. I keep getting a 404 error and that the program cant find the files.

(venv) [user@test-Ansible magic_carpet]$ pushd Cave_of_Wonders/; python3 -m http.server --bind 127.0.0.1 8888; popd;
~/programming/magic_carpet/Cave_of_Wonders ~/programming/magic_carpet
Serving HTTP on 127.0.0.1 port 8888 (http://127.0.0.1:8888/) ...
127.0.0.1 - - [26/Apr/2021 17:06:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:06:16] "GET /Cisco/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:06:17] "GET /Cisco/IOS_XE/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:06:20] "GET /Cisco/IOS_XE/Learned_ARP/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:06:25] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:06:25] "GET /src/netjsongraph.css HTTP/1.1" 404 -
127.0.0.1 - - [26/Apr/2021 17:06:25] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:06:25] "GET /src/netjsongraph-theme.css HTTP/1.1" 404 -
127.0.0.1 - - [26/Apr/2021 17:06:25] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:06:25] "GET /lib/d3.min.js HTTP/1.1" 404 -
127.0.0.1 - - [26/Apr/2021 17:06:25] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:06:25] "GET /src/netjsongraph.js HTTP/1.1" 404 -

I tried to just copy the src directory to root but that didnt work either

(venv) [user@test-Ansible magic_carpet]$ ls /src/
netjsongraph.css  netjsongraph.js  netjsongraph-theme.css  netjsonWorker.js.js
(venv) [user@test-Ansible magic_carpet]$ pushd Cave_of_Wonders/; python3 -m http.server --bind 127.0.0.1 8888; popd;
~/programming/magic_carpet/Cave_of_Wonders ~/programming/magic_carpet
Serving HTTP on 127.0.0.1 port 8888 (http://127.0.0.1:8888/) ...
127.0.0.1 - - [26/Apr/2021 17:17:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:17:14] "GET /Cisco/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:17:15] "GET /Cisco/IOS_XE/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:17:23] "GET /Cisco/IOS_XE/Learned_ARP/ HTTP/1.1" 200 -
127.0.0.1 - - [26/Apr/2021 17:17:26] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:17:26] "GET /src/netjsongraph.css HTTP/1.1" 404 -
127.0.0.1 - - [26/Apr/2021 17:17:26] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:17:26] "GET /src/netjsongraph-theme.css HTTP/1.1" 404 -
127.0.0.1 - - [26/Apr/2021 17:17:26] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:17:26] "GET /lib/d3.min.js HTTP/1.1" 404 -
127.0.0.1 - - [26/Apr/2021 17:17:26] code 404, message File not found
127.0.0.1 - - [26/Apr/2021 17:17:26] "GET /src/netjsongraph.js HTTP/1.1" 404 -

**Desktop (please complete the following information):**
 - OS: centos
 - Browser chrome

**Comment by automateyournetwork** [comment]
I think magic carpet might need to be in the root folder? I use absolute not relative paths so I believe it is looking in /src/ for the javascript files relative to if the pyATS job is being run in /magic_carpet 

Is ~/programming/magic_carpet/Cave_of_Wonders ~/programming/magic_carpe in your path? Can you try to clone / move the whole thing to root ? 

Thanks I might need to change these to relative paths but let me know if that works

**Comment by NetworkingB2A** [comment]
I was able to get it working. I spent about 2 hours trying to figure it out and ended up needing to uninstall and reinstall node js. then had to kill all sessions to my remote server and finally, I was able to get it up and running. No problem with the code, just problems trying to use my centos.
